volumes:
  database-volume:

services:
  database:
    image: postgres
    container_name: database
    restart: always
    volumes:
      - database-volume:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: next-pizza
