import type { Metadata } from "next";
import React, { Suspense } from "react";

import { Header } from "@/components/shared";

export const metadata: Metadata = {
  title: "Root",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <>
      <Suspense>
        <Header />
      </Suspense>
      <main className="h-min-screen">
        {children}
        {modal}
      </main>
    </>
  );
}
