import { Metadata } from "next";
import { Suspense } from "react";

import { Header } from "@/components/shared";
import { Container } from "@/components/ui";

export const metadata: Metadata = {
  title: "Next Pizza | Корзина",
  description: "Generated by create next app",
};

export default function CheckoutLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Suspense>
        <Header
          hasSearch={false}
          hasCart={false}
          className="bg-[#F4F1EE] marker:border-b-gray-200 fixed w-full z-10"
        />
      </Suspense>
      <main className="bg-[#F4F1EE] min-h-screen pt-32 pb-10">
        <Container>{children}</Container>
      </main>
    </>
  );
}
